apiVersion: apps/v1
kind: Deployment
metadata:
  name: karapace-registry
  labels:
    app.kubernetes.io/instance: karapace-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: karapace-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: karapace-registry
    spec:
      containers:
        - name: karapace-registry
          image: "ghcr.io/aiven/karapace:latest"
          command:
            - /bin/bash
          args: ["-c", "/opt/karapace/start.sh registry"]
          env:
            - name: KARAPACE_ADVERTISED_HOSTNAME
              value: "karapace-registry"
            - name: KARAPACE_BOOTSTRAP_URI
              value: "kafka:29092"
            - name: KARAPACE_PORT
              value: "8081"
            - name: KARAPACE_HOST
              value: "0.0.0.0"
            - name: KARAPACE_CLIENT_ID
              value: "karapace"
            - name: KARAPACE_GROUP_ID
              value: "karapace-registry"
            - name: KARAPACE_MASTER_ELIGIBILITY
              value: "true"
            - name: KARAPACE_TOPIC_NAME
              value: "_schemas"
            - name: KARAPACE_LOG_LEVEL
              value: "WARNING"
            - name: KARAPACE_COMPATIBILITY
              value: "FULL"  
          ports:
            - containerPort: 8081
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: karapace-registry
spec:
  selector:
    app.kubernetes.io/instance: karapace-registry
  ports:
    - name: karapace-registry
      port: 8081
  type: ClusterIP
