apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app.kubernetes.io/instance: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: registry
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: registry
    spec:
      initContainers:
        - name: wait-for-kafka
          image: "busybox:latest"
          command: ['/bin/sh', '-c', 'until echo srvr | nc -w 2 kafka 29092 2>/dev/null; do echo . && sleep 5; done']
      containers:
        - name: registry
          image: "confluentinc/cp-schema-registry:7.5.0"
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
          ports:
            - containerPort: 8081
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app.kubernetes.io/instance: registry
  ports:
    - name: registry
      port: 8081
  type: ClusterIP
